RealtAdmin/RealtAdmin/Controllers/FeaturesController.cs
using System.Web.Mvc;
using Moodroon.DataLayer.Core;
using Moodroon.DataLayer.Core.DTO;
using Moodroon.DataLayer.Core.Services;

namespace RealtAdmin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class FeaturesController : Controller
    {
        private readonly FeaturesService _featuresService;

        public FeaturesController()
        {
            this._featuresService = new FeaturesService(UnityFactory.Instance.Container);
        }
        [HttpGet]
        public ActionResult Index()
        {
            return this.View();
        }

        [HttpGet]
        public JsonResult GetFeatures()
        {
            return this.Json(this._featuresService.GetFeatures(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult DeleteFeature(int id)
        {
            this._featuresService.DeleteFeature(id);
            return this.Json("Success", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult AddFeature(FeaturesDto feature)    
        {
            if (!this._featuresService.AddFeature(feature))
            {
                return new HttpStatusCodeResult(500);
            }
            return this.Json(this._featuresService.GetFeatures(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult EditFeature(FeaturesDto feature)    
        {
            if (!this._featuresService.EditFeature(feature))
            {
                return new HttpStatusCodeResult(500);
            }
            return this.Json(this._featuresService.GetFeatures(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetFlatFeatures(int id)   
        {
            return this.Json(this._featuresService.GetFlatFeatures(id), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult DeleteFlatFeatures(int flatId,int featureId)
        {
            this._featuresService.DeleteFlatFeature(flatId,featureId);
            return this.Json("Succeess", JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetHouseFeatures(int id)
        {
            return this.Json(this._featuresService.GetHouseFeatures(id), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult DeleteHouseFeatures(int houseId, int featureId)    
        {
            this._featuresService.DeleteHouseFeature(houseId, featureId);
            return this.Json("Succeess", JsonRequestBehavior.AllowGet);
        }
    }
}

RealtAdmin/RealtAdmin/Controllers/FlatController.cs
using System.Web;
using System.Web.Mvc;
using Amazon.S3;
using Amazon.S3.Model;
using Moodroon.DataLayer.Core;
using Moodroon.DataLayer.Core.DTO;
using Moodroon.DataLayer.Core.Services;

namespace RealtAdmin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class FlatController : Controller
    {
        private readonly FlatService _flatService;

        public FlatController()
        {
            this._flatService = new FlatService(UnityFactory.Instance.Container);
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetFlats()
        {
            return this.Json(this._flatService.GetFlats(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult DeleteFlat(int id)
        {
            this._flatService.DeleteFlat(id);
            return this.Json("Success", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AddFlat(FlatDto flat)
        {
            this._flatService.AddFlat(flat);
            return this.Json(this._flatService.GetFlats(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EditFlat(FlatDto flat)
        {
            this._flatService.EditFlat(flat);
            return this.Json("Success", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AddFeature(int id, int featureId)
        {
            this._flatService.AddIFeature(id, featureId);
            return this.Json("Success", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult DeleteImage(int id, string url)    
        {
            this._flatService.DeleteImage(id, url);
            return this.Json("Success", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public RedirectToRouteResult UploadImage(HttpPostedFileBase file,int id)    
        {
            if (file != null)
            {

                var s3Config = new Amazon.S3.AmazonS3Config { ServiceURL = AppConfiguration.AppConfiguration.Instance.ServiceUrl };
                using (var client = Amazon.AWSClientFactory.CreateAmazonS3Client(
                    AppConfiguration.AppConfiguration.Instance.AccessKey,
                   AppConfiguration.AppConfiguration.Instance.SecretKey,
                   s3Config))
                {
                    var request = new PutObjectRequest
                    {
                        BucketName = "imagesforhotel",
                        Key = file.FileName,
                        InputStream = file.InputStream,
                        CannedACL = S3CannedACL.PublicRead
                    };
                    client.PutObject(request);
                    var url = "https://s3.amazonaws.com/" + request.BucketName + "/" + file.FileName;
                    this._flatService.AddImage(id, url);
                }
            }
            return this.RedirectToAction("Index");
        }
    }
}

RealtAdmin/RealtAdmin/Controllers/HouseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Amazon.S3;
using Amazon.S3.Model;
using Moodroon.DataLayer.Core;
using Moodroon.DataLayer.Core.DTO;
using Moodroon.DataLayer.Core.Services;

namespace RealtAdmin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class HouseController : Controller
    {
        private readonly HouseService _houseService;    

        public HouseController()
        {
            this._houseService = new HouseService(UnityFactory.Instance.Container);
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetHouses()
        {
            return this.Json(this._houseService.GetHouses(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult DeleteHouse(int id)
        {
            this._houseService.DeleteHouse(id);
            return this.Json("Success", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AddHouse(HouseDto house)
        {
            this._houseService.AddHouse(house);
            return this.Json(this._houseService.GetHouses(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EditHouse(HouseDto house)
        {
            this._houseService.EditHouse(house);
            return this.Json("Success", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AddFeature(int id, int featureId)
        {
            this._houseService.AddIFeature(id, featureId);
            return this.Json("Success", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult DeleteImage(int id, string url)
        {
            this._houseService.DeleteImage(id, url);
            return this.Json("Success", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public RedirectToRouteResult UploadImage(HttpPostedFileBase file, int id)
        {
            if (file != null)
            {

                var s3Config = new Amazon.S3.AmazonS3Config { ServiceURL = AppConfiguration.AppConfiguration.Instance.ServiceUrl };
                using (var client = Amazon.AWSClientFactory.CreateAmazonS3Client(
                    AppConfiguration.AppConfiguration.Instance.AccessKey,
                   AppConfiguration.AppConfiguration.Instance.SecretKey,
                   s3Config))
                {
                    var request = new PutObjectRequest
                    {
                        BucketName = "imagesforhotel",
                        Key = file.FileName,
                        InputStream = file.InputStream,
                        CannedACL = S3CannedACL.PublicRead
                    };
                    client.PutObject(request);
                    var url = "https://s3.amazonaws.com/" + request.BucketName + "/" + file.FileName;
                    this._houseService.AddImage(id, url);
                }
            }
            return this.RedirectToAction("Index");
        }

    }
}

RealtAdmin/RealtAdmin/Controllers/RealtTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Moodroon.DataLayer.Core;
using Moodroon.DataLayer.Core.DTO;
using Moodroon.DataLayer.Core.Services;

namespace RealtAdmin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RealtTypeController : Controller
    {
        private readonly RealtTypeService _realtTypeService;

        public RealtTypeController()
        {
            this._realtTypeService = new RealtTypeService(UnityFactory.Instance.Container);
        }

        [HttpGet]
        public ActionResult Index()
        {
            return this.View();
        }

        [HttpGet]
        public JsonResult GetRealtTypes()
        {
            return this.Json(this._realtTypeService.GetRealtTypes(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult DeleteFeature(int id)
        {
            this._realtTypeService.DeleteRealt(id);
            return this.Json("Success", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult AddFeature(RealtTypeDto realt)
        {
            if (!this._realtTypeService.AddRealt(realt))
            {
                return new HttpStatusCodeResult(500);
            }
            return this.Json(this._realtTypeService.GetRealtTypes(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult EditRealt(RealtTypeDto realt)   
        {
            if (!this._realtTypeService.EditRealt(realt))
            {
                return new HttpStatusCodeResult(500);
            }
            return this.Json(this._realtTypeService.GetRealtTypes(), JsonRequestBehavior.AllowGet);
        }
    }
}

RealtAdmin/RealtAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Realt admin page </title>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/icon?family=Material+Icons">

    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    <!-- Bootstrap Material Design -->
    <link rel="stylesheet" href="~/Scripts/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/Scripts/lib/font-awesome-css/css/font-awesome.css" />
    <link rel="stylesheet" href="~/Content/css/angular-snap.css" />
    <link rel="stylesheet" href="~/Scripts/lib/angular-material/angular-material.min.css" />
    <link rel="stylesheet" href="~/Scripts/lib/angular-material/angular-material.layouts.min.css" />
    <link rel="stylesheet" href="~/Scripts/lib/font-awesome-css/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/Content/css/bootstrap-material-design.min.css" />
    <link rel="stylesheet" href="~/Content/css/ripples.min.css" />
    <link rel="stylesheet" href="~/Content/bootstrap-material-datetimepicker.css" />
    <style>
        .loading-spiner {
            position: absolute;
            left: 50%;
            top: 50%;
            z-index: 9999999999999;
        }
    </style>

</head>
<body ng-app="yapp" style="overflow: auto !important; overflow-y: scroll;">
    <div class="bs-component" ng-cloak="">
        <div class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="javascript:void(0)">
                        Realt admin page
                        <div class="ripple-container"></div>
                    </a>
                </div>
                <div class="navbar-collapse collapse navbar-responsive-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="@Url.Action("Index","Flat")">Flats</a></li>
                        <li><a href="@Url.Action("Index", "House")">Houses</a></li>
                        <li><a href="@Url.Action("Index", "Features")">Features</a></li>
                        <li><a href="@Url.Action("Index","RealtType")">Realt types</a></li>
                    </ul>
                    <form class="navbar-form navbar-left">
                        <div class="form-group is-empty">
                            <input type="text" class="form-control col-md-8" placeholder="Search">
                            <span class="material-input"></span>
                        </div>
                    </form>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            @if (this.User.Identity.IsAuthenticated)
                            {
                                <a>
                                    <i class="material-icons">account_circle</i>
                                    @User.Identity.Name
                                </a>
                            }
                        </li>
                        <li>
                            <a href="javascript:document.getElementById('logoutForm').submit()"><i class="fa fa-sign-out"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div id="source-button" class="btn btn-primary btn-xs" style="display: none;">&lt; &gt;</div>
    </div>
    <div class="container-fluid">
        @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
        {
            @Html.AntiForgeryToken()

        }
        <div class="loading-spiner" data-loading>
            <div>
                <img class="img-responsive" style="height: 10%; width: 10%" src="~/Content/images/loadingGif.gif" />
            </div>
        </div>
        @RenderBody()
    </div>

    <script src="~/Scripts/jquery-2.2.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/js/material.min.js"></script>
    <script src="~/Scripts/lib/angular/angular.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc2/angular-material.min.js"></script>
    <script src="~/Scripts/lib/angular-aria/angular-aria.min.js"></script>
    <script src="~/Scripts/lib/angular-messages/angular-messages.min.js"></script>
    <script src="~/Scripts/lib/angular-animate/angular-animate.js"></script>
    <script src="~/Scripts/lib/angular-snapjs/src/scripts/snap.js"></script>
    <script src="~/Scripts/lib/angular-local-storage/dist/angular-local-storage.min.js"></script>
    <script src="~/Scripts/lib/angular-loading-bar/src/loading-bar.js"></script>
    <script src="~/Scripts/js/app.js"></script>


    @RenderSection("scripts", required: false)
</body>
</html>